# Generated by Django 5.2 on 2026-01-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
