# Generated by Django 5.2 on 2026-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
