# Generated by Django 5.2 on 2026-02-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_message_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
