# Generated by Django 5.2 on 2026-02-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chat_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='role',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
